services:
  db:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: auth_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/mydb?schema=public
      NODE_ENV: development
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma generate --schema=./prisma/schema.prisma &&
        npx prisma migrate deploy &&
        npm run start
      "

volumes:
  pgdata:
